---
name: Test
"on": push

permissions:
  contents: read

env:
  APP_HOST: localhost
  APP_PORT: 3000
  APP_EMAIL_FROM: test@example.com
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432
  TEST_PORT: 4000

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432/tcp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3.2.0
      - uses: 'ex-actions/setup-mix@main'
      - run: mix ecto.create
      - run: mix ecto.migrate
      - run: mix test
